# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: "Getting started"
  link: "/getting-started"
- label: "Theme"
  link: "/theme"
- label: "Components"
  items:
    - label: "Typography"
      link: "/components/typography"
    - label: "Cards"
      link: "/components/cards"
    - label: "Buttons"
      link: "/components/buttons"
    - label: "Horizontal Rule"
      link: "/components/hr"
    - label: "Alerts"
      link: "/components/alerts"
    - label: "Avatars"
      link: "/components/avatar"
    - label: "Badges"
      link: "/components/badges"
    - label: "Dropdown"
      link: "/components/dropdown"
    - label: "Dropdown Input"
      link: "/components/dropdown-input"
    - label: "Modals"
      link: "/components/modals"
    - label: "Hook-driven modals"
      link: "/components/hook-driven-modals"
    - label: "Hook-driven confirm"
      link: "/components/hook-confirm"
    - label: "Ribbons"
      link: "/components/ribbons"
    - label: "Spinners"
      link: "/components/spinners"
    - label: "Steps"
      link: "/components/steps"
    - label: "Tables"
      link: "/components/tables"
    - label: "Timeline"
      link: "/components/timeline"
- label: "Utilities"
  items:
    - label: "Colors"
      link: "/utilities/colors"
    - label: "Margins"
      link: "/utilities/margins"
