# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: "Getting started"
  link: "/getting-started"
- label: "Theme"
  link: "/theme"
- label: "Changelog"
  link: "/changelog"
- label: "Components"
  items:
    - label: "Typography"
      link: "/components/typography"
    - label: "Cards"
      link: "/components/cards"
    - label: "Buttons"
      link: "/components/buttons"
    - label: "Inputs"
      link: "/components/input"
    - label: "Dropdown"
      link: "/components/dropdown"
    - label: "Dropdown Input"
      link: "/components/dropdown-input"
    - label: "Select Group"
      link: "/components/select-group"
    - label: "Enclosed Select Group"
      link: "/components/enclosed-select-group"
    - label: "Segmented Control"
      link: "/components/segmented-control"
    - label: "Horizontal Rule"
      link: "/components/hr"
    - label: "Alerts"
      link: "/components/alerts"
    - label: "Avatars"
      link: "/components/avatar"
    - label: "Badges"
      link: "/components/badges"
    - label: "Modals"
      link: "/components/modals"
    - label: "Hook-driven modals"
      link: "/components/hook-driven-modals"
    - label: "Hook-driven confirm"
      link: "/components/hook-confirm"
    - label: "Ribbons"
      link: "/components/ribbons"
    - label: "Spinners"
      link: "/components/spinners"
    - label: "Steps"
      link: "/components/steps"
    - label: "Tables"
      link: "/components/tables"
    - label: "Tables v2"
      link: "/components/table-v2"
    - label: "Timeline"
      link: "/components/timeline"
    - label: "Navbar"
      link: "/components/navbar"
- label: "Utilities"
  items:
    - label: "Colors"
      link: "/utilities/colors"
    - label: "Margins"
      link: "/utilities/margins"
